site_name: Hong Kong Fire Documentary
site_url: https://Hong-Kong-Emergency-Coordination-Hub.github.io/Hong-Kong-Fire-Documentary/
repo_url: https://github.com/Hong-Kong-Emergency-Coordination-Hub/Hong-Kong-Fire-Documentary
repo_name: Hong-Kong-Fire-Documentary

theme:
  name: material
  language: zh-Hant
  features:
    - navigation.tabs
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
  palette: 
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

docs_dir: content

extra_css:
  - assets/stylesheets/extra.css


copyright: 'Copyright &copy; 2025 Hong Kong Fire Documentary. This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.'

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: zh-Hant
          default: true
          name: 繁體中文
          build: true
        - locale: en
          name: English
          build: true
      nav_translations:
        zh-Hant:
          Home: 主頁
          Timeline: 時間線
          Videos: 現場片段
          News: 新聞報道
          Analysis: 技術分析
          Support: 支援資訊
          Photos: 圖片紀錄
          Residents: 居民討論
          Docs: 政府文件

nav:
  - Home: index.md
  - Timeline: timeline/README.md
  - Videos: videos/README.md
  - News: news/README.md
  - Analysis: analysis/README.md
  - Support: support/README.md
  - Photos: photos/README.md
  - Residents: residents/README.md
  - Docs: docs/README.md
